version: 1
disable_existing_loggers: true
incremental: false

formatters:
  default:
    format: '[%(asctime)s %(filename)s:%(lineno)d] %(levelname)-7s %(message)s'
  message_only:
    format: '%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
  console_werkzeug:
    class: logging.StreamHandler
    level: DEBUG
    formatter: message_only

loggers:
  flask.app:
    handlers: [console]
    propagate: false
    level: DEBUG
  werkzeug:
    handlers: [console_werkzeug]
    propagate: false
    level: INFO

root:
  handlers: [console]
  level: WARNING
