language: python
python:
  - "3.7"
# command to install dependencies
install:
  - export FLASK_APP=parrot._cli_app
  - export FLASK_ENV=development
  - pip install -r requirements/dev.txt
  - flask --version
# command to run tests
script:
  - pytest --cov-report term-missing --cov=parrot tests/
