# -*- coding: utf-8 -*-
"""
    :copyright: © 2010-2019 by Farhan Ahmed.
    :license: BSD, see LICENSE for more details.
"""

_VERSION                    = "1"
VERSION_URL                 = f'/{_VERSION}'
DEFAULT_HEADER              = {'content-type': 'application/json'}
DEFAULT_STATUS_CODE         = 200
DEFAULT_RESPONSE_LAG        = 0.20
DEFAULT_METHOD              = 'GET'
DEFAULT_SERVICE_NAME        = 'Parrot Mock API Service'
RESPONSE_INJECTION_ENDPOINT = 'parrot'
EMPTY_CONTENT               = 'No content provided.'
DEFAULT_HOSTNAME            = 'localhost'
PARROT_OPTION_LOAD_CONFIG   = 'CONFIG'
PARROT_OPTION_CORS_ENABLED  = 'CORS_ENABLED'
PARROT_OPTION_LAG           = 'RESPONSE_LAG'
PARROT_OPTION_FUZZ          = 'HOT_FUZZ'

REQUEST_HEADER_SESSION_KEY            = "X-Session-Identifier"
SESSION_USER_AUTHENTICATION_TOKEN_KEY = "session-token"

CONFIGURATION_NAME_KEY        = 'name'
CONFIGURATION_BASE_URL_KEY    = 'base_url'
CONFIGURATION_ENDPOINTS_KEY   = 'endpoints'
CONFIGURATION_URL_KEY         = 'url'
CONFIGURATION_RESPONSES_KEY   = 'responses'
CONFIGURATION_CONTENT_KEY     = 'content'
CONFIGURATION_DESCRIPTION_KEY = 'description'
CONFIGURATION_IDENTIFIER_KEY  = 'identifier'

RESPONSE_PAYLOAD_ENDPOINT_KEY    = 'endpoint'
RESPONSE_PAYLOAD_METHOD_KEY      = 'method'
RESPONSE_PAYLOAD_STATUS_CODE_KEY = 'status_code'
RESPONSE_PAYLOAD_PARAMETERS_KEY  = 'parameters'
RESPONSE_PAYLOAD_HEADERS_KEY     = 'headers'
RESPONSE_PAYLOAD_CONTENT_KEY     = 'content'
RESPONSE_PAYLOAD_LAG_KEY         = 'lag'
RESPONSE_PAYLOAD_FUZZ_KEY        = 'fuzz'
RESPONSE_RESULT_SUCCESS          = 0
RESPONSE_ERROR_KEY               = 'error'
RESPONSE_ERROR_CODE_KEY          = 'code'
RESPONSE_ERROR_LIST_KEY          = 'errors'
RESPONSE_MESSAGE_KEY             = 'message'

RESPONSE_PAYLOAD_INJECTION_STATUS_KEY = 'status'

ALLOWED_METHODS   = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'TRACE', 'OPTIONS']
INJECTION_METHODS = ['OPTIONS', 'POST', 'PUT', 'DELETE', 'PATCH']

HTTP_STATUS_CODE_OK                    = 200
HTTP_STATUS_CODE_NO_CONTENT            = 204
HTTP_STATUS_CODE_BAD_REQUEST           = 400
HTTP_STATUS_CODE_NOT_FOUND             = 404
HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_CODE_FORBIDEN              = 403
HTTP_STATUS_CODE_UNAUTHROIZED          = 401
